version: '3'
services:
  db:
    image: ghcr.io/viniciusbrg/teastore-monolithic/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
  webui:
    image: ghcr.io/viniciusbrg/teastore-monolithic/teastore-webui
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
    ports:
      - "8080:8080"